food/urls.py
from django.urls import path
from food.views import *
app_name='tasty'
urlpatterns=[
    path('biriyani/',biriyani,name='biriyani')
]

ola/urls.py
from django.contrib import admin
from django.urls import path,include
import food,shopping
from travel.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('shopping/',include('shopping.urls')),
    path('kerala/',kerala,name='kerala'),
]

shopping/urls.py
from django.urls import path
from shopping.views import *
app_name='new'
urlpatterns=[
    path('car/',car,name='car'),
]

food/models.py
from django.db import models

# Create your models here.

shopping/models.py
from django.db import models

# Create your models here.

travel/models.py
from django.db import models

# Create your models here.

food/views.py
from django.shortcuts import render

# Create your views here.
def biriyani(request):
    return render(request,'biriyani.html')

shopping/views.py
from django.shortcuts import render

# Create your views here.
def car(request):
    return render(request,'car.html')

travel/views.py
from django.shortcuts import render

# Create your views here.
def kerala(request):
    return render(request,'kerala.html')

templates/biriyani.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>it is a biriyani resturent</h1>
        <a href="{% url 'new:car' %}">go to car</a>
    </center>
</body>
</html>

templates/car.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>it is my favt car</h1>
        <a href="{% url 'tasty:biriyani' %}">go to resturent </a>
    </center>
</body>
</html>

templates/kerala.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>it is my favt place</h1>
        <a href="{% url 'new:car' %}">go to car and enjoy the trip</a>
        <a href="{% url 'tasty:biriyani' %}">go to resturent </a>
    </center>
</body>
</html>